# Generated by Django 2.1.15 on 2021-08-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210826_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tage',
            new_name='tags',
        ),
    ]
